### ISSUE TITLE
After Running command  llmtune run ./config.yml not getting output

### ISSUE THREAD

**Issue by jeetendraabvv** [georgian-io/LLM-Tuning-Hub#176]
PS C:\Users\Administrator> llmtune run ./config.yml
C:\ProgramData\anaconda3\envs\llm_tkit\Lib\site-packages\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Administrator\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Administrator\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\Administrator\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
───────────────────────────────── Loading Data ─────────────────────────────────
Loading formatted dataset from directory experiment\sHR8ns\dataset                                                                                                             
╭─ Train Example - Raw ────────────────╮╭─ Inference Example - Raw ────────────╮
│ ┏━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┓ ││ ┏━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┓ │
│ ┃ output    ┃ input     ┃ instruc… ┃ ││ ┃ output    ┃ input    ┃ instruct… ┃ │
│ ┡━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━┩ ││ ┡━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━┩ │
│ │ This is a │ The city  │ Identify │ ││ │ Early,    │ She left │ Rearrange │ │
│ │ grade 3   │ lights    │ the      │ ││ │ she left  │ the      │ the       │ │
│ │ level     │ that      │ level of │ ││ │ the       │ party    │ following │ │
│ │ poem.     │ spring to │ this     │ ││ │ party.    │ early    │ sentence  │ │
│ │           │ life,     │ poem.    │ ││ │           │          │ to make   │ │
│ │           │ Bright    │          │ ││ │           │          │ the       │ │
│ │           │ fires to  │          │ ││ │           │          │ sentence  │ │
╰──────────────────────────────────────╯╰──────────────────────────────────────╯
╭─ Train Example - Formatted ──────────╮╭─ Inference Example - Formatted ──────╮
│ Below is an instruction that         ││ Below is an instruction that         │
│ describes a task.  Write a response  ││ describes a task.  Write a response  │
│ that appropriately completes the     ││ that appropriately completes the     │
│ request.  ### Instruction: Identify  ││ request.  ### Instruction: Rearrange │
│ the level of this poem. ### Input:   ││ the following sentence to make the   │
│ The city lights that spring to life, ││ sentence more interesting. ###       │
│ Bright fires to the endless night,   ││ Input: She left the party early ###  │
│ A promise of a better life           ││ Output:                              │
│ That never quite can put things      ││                                      │
│ right. ### Output:This is a grade 3  ││                                      │
│ level poem.                          ││                                      │
╰──────────────────────────────────────╯╰──────────────────────────────────────╯
Dataset Saved at experiment\sHR8ns\dataset
Post-Split data size:
Train: 500
Test: 25
──────────────────────────────── 😃 Finetuning ─────────────────────────────────
Fine-Tuned Model Found at experiment\sHR8ns\weights... skipping training
────────────────────────────────── 🧐 Testing ──────────────────────────────────
Inference Results Found at experiment\sHR8ns\results

**Comment by jeetendraabvv** [comment]
After running second time, not generating any file/folder in experiment folder. Kindly help

**Comment by benjaminye** [comment]
Try deleting `experiment\sHR8ns` folder and running the script again.

**Comment by benjaminye** [comment]
Closed due to inactivity. Please feel free to reopen this issue if assistance is still required.
